# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('happiness_gain_rate', models.IntegerField(default=1)),
                ('happiness_loss_rate', models.IntegerField(default=1)),
                ('hunger_gain_rate', models.IntegerField(default=1)),
                ('hunger_loss_rate', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
