# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='kind',
            new_name='species',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
