# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20161129_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Species',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='species',
            new_name='name',
        ),
    ]
