# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20161129_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='hunger_gain_rate',
            new_name='fullness_gain_rate',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='hunger_loss_rate',
            new_name='fullness_loss_rate',
        ),
    ]
