# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20161129_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='current_fullness',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pet',
            name='current_happiness',
            field=models.IntegerField(default=5),
        ),
    ]
